### ISSUE TITLE
Requesting Invite

### ISSUE THREAD

**Issue by mwhit74** [open-struct-engineer/watch_for_invite#1]
hey! yea I've started working on an open source structural engineering platform myself, you can see some of my ideas over on my github page and bit more about them here: https://mwhit74.github.io/index.html

I'm not really sure how this invite thing is supposed to work or how to request so I thought I would start here, opening an issue.

**Comment by buddyd16** [comment]
Hey thanks for reaching out looks like you have some good stuff underway. You should get/have an invite to joint the group and it's general chat channel. 

Most everyone in the group are also members of the Eng-Tips forums. 

Group is still in it's infancy so no real guidelines the 3 repositories out there are my attempt to lay some foundation work on some programs that I think everyone would likely get some use from in their day to day work with the ConcreteXSection being my personal pipe dream program to cover bi-axial analysis for a general concrete cross-section with arbitrary reinforcement and pre-stress for each of the major building codes, if your familiar with SpColumn that is kind of my goal.
